# Generated by Django 3.1 on 2020-08-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200814_1327'),
        ('tweets', '0003_auto_20200826_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='new_like',
        ),
        migrations.AddField(
            model_name='like',
            name='tweet',
            field=models.ForeignKey(default=76, on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='liker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
