# Generated by Django 3.1 on 2020-09-06 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200902_1519'),
        ('tweets', '0009_auto_20200902_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retweet',
            name='tweet_ptr',
        ),
        migrations.AddField(
            model_name='retweet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retweet',
            name='id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retweet',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retweet',
            name='text',
            field=models.CharField(default='', max_length=280),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retweet',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
