# Generated by Django 3.1 on 2020-09-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_auto_20200906_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retweet',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
