# Generated by Django 3.1.1 on 2020-09-17 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20200917_1603'),
        ('tweets', '0011_auto_20200906_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweet_profile', to='profiles.profile'),
        ),
        migrations.DeleteModel(
            name='Retweet',
        ),
    ]
