# Generated by Django 3.1.1 on 2020-09-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_auto_20200917_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='retweet_profile',
        ),
    ]
