# Generated by Django 3.1.1 on 2020-09-23 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0014_auto_20200923_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='reply',
        ),
        migrations.AddField(
            model_name='tweet',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tweets.tweet'),
        ),
    ]
