# Generated by Django 3.1 on 2020-09-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200902_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
