# Generated by Django 3.1.1 on 2020-09-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20200917_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
